namespace: "ji_podhead"
name: "netbox_docker_podman"
description:  "netbox for docker and podman"
version: "1.1.0"
readme: "README.md"
authors:
    - "ji-podhead (https://https://www.github.com/ji-podhead)"
dependencies:
    community.general: ">=0.0.0"
license:
    - "MIT"
tags:
    - netbox
    - network_automation
    - podman
    - container
    - direct_ansible_usage
    - automatic_superuser_creation
    - automatic_usertoken_creation
    - ip_assignment
    - multiple_networks
    - waits_for_database_migration
    - podman_compose
    - docker_compose
    - network_planing
    - postgresql

repository: "https://www.github.com/the-pod-shop/netbox_docker_podman_collection"



