
- name: remove old folder
  ansible.builtin.shell: rm -rf /tmp/netbox-docker
  
- name: Clone NetBox Docker repository
  git:
    repo: 'https://github.com/netbox-community/netbox-docker.git'
    dest: /tmp/netbox-docker
    version: release

