- name: Remove old containers and volumes
  shell: |
    cd /tmp/netbox-docker
    {{compose_path}} down
    if "{{ platform }}" == "podman":
      podman volume rm -f netbox-docker_netbox-postgres-data netbox-docker_netbox-redis-data netbox-docker_netbox-redis-cache-data netbox-docker_netbox-media-files netbox-docker_netbox-reports-files netbox-docker_netbox-scripts-files
    else:
      docker volume rm -f netbox-docker_netbox-postgres-data netbox-docker_netbox-redis-data netbox-docker_netbox-redis-cache-data netbox-docker_netbox-media-files netbox-docker_netbox-reports-files netbox-docker_netbox-scripts-files
  ignore_errors: yes