- name: get git
  ansible.builtin.dnf:
    name:
      - git
- name: get pc
  ansible.builtin.pip:
    name:
      - podman-compose 
- name: remove old folder
  ansible.builtin.shell: rm -rf /tmp/netbox-docker
  
