---
use_default_network: true
networks:
  - name: default

# --------> container net <----------  
postgres:
  networks:
    - default
netbox:
  networks:
    - default
redis:
  networks:
    - default
redis_cache:
  networks:
    - default
netbox_housekeeping:
  networks:
    - default
netbox_worker:
  networks:
    - default
# --------> overrides <----------
overrides: 
  services:
    netbox:
      ports: 
        - 8000:8080
